-- automatically generated by BNF Converter
module Main where


import           System.IO                      ( stdin
                                                , hGetContents
                                                )
import           System.Environment             ( getArgs
                                                , getProgName
                                                )
import           System.Exit                    ( exitFailure
                                                , exitSuccess
                                                )
import           Control.Monad                  ( when )

import           Samoyeet.Lex
import           Samoyeet.Par
import           Samoyeet.Skel
import           Samoyeet.Print
import           Samoyeet.Abs




import           Samoyeet.ErrM
import           Evaluate                       ( execInterpretMonad )
import           TypeChecker                    ( execTypeCheckerMonad )

type ParseFun = [Token] -> Err Program

myLLexer = myLexer

type Verbosity = Int

putStrV :: Verbosity -> String -> IO ()
putStrV v s = when (v > 1) $ putStrLn s

runFile :: Verbosity -> ParseFun -> FilePath -> IO ()
runFile v p f = putStrLn f >> readFile f >>= run v p

run :: Verbosity -> ParseFun -> String -> IO ()
run v p s =
  let ts = myLLexer s
  in  case p ts of
        Bad s -> do
          putStrLn "\nParse              Failed...\n"
          putStrV v "Tokens:"
          putStrV v $ show ts
          putStrLn s
          exitFailure
        Ok entire@(Program p) -> do
          putStrLn "\nParse Successful!"
          showTree v entire
          putStrLn "\nDoing what I was told please!\n"
          execTypeCheckerMonad p
          execInterpretMonad p
          exitSuccess


showTree :: Int -> Program -> IO ()
showTree v tree = do
  putStrV v $ "\n[Abstract Syntax]\n\n" ++ show tree
  putStrV v $ "\n[Linearized tree]\n\n" ++ printTree tree

usage :: IO ()
usage = do
  putStrLn $ unlines
    [ "usage: Call with one of the following argument combinations:"
    , "  --help          Display this help message."
    , "  file            Parse content of files verbosely."
    ]
  exitFailure

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> usage
    fs         -> mapM_ (runFile 2 pProgram) fs





